# Site settings
theme: jekyll-theme-minimal
title: Arduino-SC
description: "Grupo de Usuários Arduino de Santa Catarina"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arduinosc.org" # the name of your domain
logo: img/se_joga_nessa_onda.jpg
markdown: kramdown
google_analytics: UA-116538996-1
show_downloads: false

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

# Pagination
paginate: 5
pagination_path: "/:num"

# Build settings
highlighter: rouge
timezone: America/Sao_Paulo
permalink: pretty
