# Site settings
theme: jekyll-theme-minimal
title: Arduino-SC
description: "Arduino-SC - Grupo de Usuários Arduino de Santa Catarina"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.arduinosc.org" # the name of your domain
logo: img/arduino-logo-clean.png
markdown: kramdown
google_analytics: UA-116538996-1
google_verification: AIzaSyByw7AqzbYASj16OB1LbBilo7vZtunHP0I
show_downloads: false
